import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-3xl font-bold'>Next tailwind Amazona</h1>
     
    </div>
  )
}


h) HelpDeskStaff (extends Staff super class)
•	HelpDeskStaff ( ) - This function is the constructor method for the class and is run every time an object of this class is created.

i) GymReceptionistStaff (extends Staff super class)
 j) InstructorStaff (extends Staff super class)



